### ISSUE TITLE
data目录下已经是完整数据集了吗？

### ISSUE THREAD

**Issue by bojone** [Pzoom522/HistSumm#1]
你好，今天在Arxiv上刚看到这篇文章，觉得这个任务颇有意思。我看data下的数据集只有很少，应该不是完整的数据集吧？请问完整的数据集可以申请吗？

**Comment by Pzoom522** [comment]
苏剑林大佬好！谢谢关注我们的工作:heart:

很不幸，如我们在论文所提到的，本次发布的两种语言各100条数据集已经是完整的语料了。现阶段无法继续扩大规模的原因在于，标注这个任务的数据集的成本极其高昂；因此，它应全部用于**模型测试**而非训练。我们在EACL 2021会议前后，会完整开放我们预训练好的词向量、迁移学习摘要模型等，您届时可以在此基础上探索**不依赖大规模有标注训练数据集**来完成古文摘要任务的新策略。

如您对我们的项目或者论文有任何问题，欢迎留言讨论~
